### ISSUE TITLE
Example messenger.js and template.js have unexpected token issue

### ISSUE THREAD

**Issue by everythingswift** [wit-ai/node-wit#43]
Unable to figure out how to navigate away from these issues. Do not let me run the examples as expected for testing/integration to proceed. Any guidance or help or if this is a real issue, please acknowledge. 

**Issue with template.js**
[ec2-user@ip-122-51-20-10 node-wit]$ node --harmony examples/template.js MYWITTOKEN

/home/ec2-user/node_modules/node-wit/examples/template.js:7
const token = (() => {
                ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Issue with messenger.js**
[ec2-user@ip-122-51-20-10 node-wit]$ node --harmony examples/messenger.js

/home/ec2-user/node_modules/node-wit/examples/messenger.js:53
const fbMessage = (recipientId, msg, cb) => {
                                          ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by everythingswift** [comment]
Had to install packages 'hapi' for this error to not come. It'd be better if a heads up is provided for the dependency libraries than leaving the issue just as is.

**Comment by patapizza** [comment]
What version of node are you running?
