### ISSUE TITLE
*/node_modules/node-wit/lib/wit.js:18

### ISSUE THREAD

**Issue by hshah8831** [wit-ai/node-wit#51]
after upgrading to the latest sdk, I get this error

node_modules/node-wit/lib/wit.js:18
  const {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17) ...

**Comment by Sigmus** [comment]
Looks like your node doesn't understand [Destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

**Comment by hshah8831** [comment]
Running my server on heroku, will have to check the version. Anyways, thanks a lot for the heads up.
Closing the issue

**Comment by Sigmus** [comment]
Try adding the following key to your `package.json` and deploy again:

```
"engines": {
    "node": "6.2.2"
  }
```
