### ISSUE TITLE
When I run the quickstart.js, I have got this error.

### ISSUE THREAD

**Issue by dezzzus** [wit-ai/node-wit#55]
> string_decoder.js:68
>   if (buf.length === 0)
>          ^

TypeError: Cannot read property 'length' of null
    at StringDecoder.write (string_decoder.js:68:10)
    at Interface._normalWrite (readline.js:335:30)
    at Interface.write (readline.js:326:49)
    at prompt (F:\github\node-wit\lib\wit.js:143:10)
    at Wit.interactive (F:\github\node-wit\lib\wit.js:145:5)
    at Object.<anonymous> (F:\github\node-wit\examples\quickstart.js:60:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

**Comment by sandeepgiri** [comment]
I'm getting the same error on both basic.js and quickstart.js (using node 6.4.0, node-wit 4.1.0). 

Earlier I was using Node 4.5.0 and had to add --harmony_destructuring to run, but then I was getting "node-wit not found" type error

**Comment by melissamcewen** [comment]
I had this for a bit today when I deployed to Heroku and it was because the code that was triggered was meant for my console testing environment. This answer helped me make sure it was only set up then:
http://stackoverflow.com/questions/6398196

```
if (require.main === module) {
  console.log("Bot testing mode.");
  const client = new Wit({accessToken, actions});
  interactive(client);
}

```
