### ISSUE TITLE
deployment fails on heroku

### ISSUE THREAD

**Issue by crosofg** [wit-ai/node-wit#62]
I get following error upon deployment to heroku.

```
2016-07-18T14:18:06.984747+00:00 heroku[web.1]: State changed from crashed to starting
2016-07-18T14:18:08.283334+00:00 heroku[web.1]: Starting process with command `node index.js`
2016-07-18T14:18:10.527022+00:00 app[web.1]: /app/index.js:220
2016-07-18T14:18:10.527061+00:00 app[web.1]:                     const {text, attachments} = event.message;
2016-07-18T14:18:10.527096+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-07-18T14:18:10.527096+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-07-18T14:18:11.566180+00:00 heroku[web.1]: Process exited with status 1
2016-07-18T14:18:11.581860+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by Sigmus** [comment]
Try adding this to your `package.json`:

```
"engines": {
    "node": "6.2.2"
  }
```

**Comment by crosofg** [comment]
solved

**Comment by MetaNaveen** [comment]
**The below steps resolved my solution:**

Editing package.json as:

...
"engines": {
"node": "5.0.0",
"npm": "4.6.1"
},
...

and Server.js as:

...
var port = process.env.PORT || 3000;
app.listen(port, "0.0.0.0", function() {
console.log("Listening on Port 3000");
});
...
