### ISSUE TITLE
no matching user

### ISSUE THREAD

**Issue by crosofg** [wit-ai/node-wit#64]
```
Error: (#100) No matching user found
2016-07-18T22:20:41.674308+00:00 app[web.1]:     at fetch.then.then.json (/app/services/wit.js:103:23)
2016-07-18T22:20:41.674324+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by tdquang** [comment]
Same issue.

**Comment by PaulCaillau** [comment]
Also interested in this issue, I have the same Error

**Comment by tareshss** [comment]
just add a check for the bot's message. see commit for details.
