### ISSUE TITLE
Get action name on error

### ISSUE THREAD

**Issue by Godoy** [wit-ai/node-wit#89]
Hi!

I only have the default action `send` in my script. When I perform another action that does not exist, I want to get your name in the catch:

```
    client.runActions("session-" + res.message.user["id"], query, context)
      .then((ctx) => {
        context = ctx;
      })
      .catch((err) => {
        console.log("Error ok!");
        console.error(err);
      })
```

The `console.error(err);` returns:

```
Error: No 'analytics profiles' action found.
  at throwIfActionMissing (/.../node_modules/node-wit/lib/wit.js:194:11)
  at /.../node_modules/node-wit/lib/wit.js:120:9
  at process._tickCallback (internal/process/next_tick.js:103:7)
```

I need to parse this error as a string to get failled action name `analytics profiles`? There is a way to get the action name to build my fallback?

Thanks!

**Comment by Godoy** [comment]
Sorry, I solved using a simple default action `missing`:

![screen shot 2016-09-08 at 1 45 13 pm](https://cloud.githubusercontent.com/assets/1420198/18358236/86e1f8da-75ca-11e6-9817-8ef2ef4cfbc4.png)

and..

```
const actions = {
      ....,
      missing(request) {
        console.error("missing");
        const { entities } = request;
        const botCommand = firstEntityValue(entities, "command");

        robot.emit(botCommand);
        ...
```
